version: '3.8'

services:
  central-server:
    build: ./server
    container_name: central-server-1
    ports:
      - "8080:8080"
    networks:
      - fl-network

  client-1:
    build: ./clients
    container_name: client-1
    volumes:
      - ./data/client_1/data.csv:/app/data.csv
    environment:
      - SERVER_ADDRESS=central-server:8080
    depends_on:
      - central-server
    networks:
      - fl-network

  client-2:
    build: ./clients
    container_name: client-2
    volumes:
      - ./data/client_2/data.csv:/app/data.csv
    environment:
      - SERVER_ADDRESS=central-server:8080
    depends_on:
      - central-server
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge